<?php
/*
Template Name: Contributors Template
 */
?>
<?php get_header(); ?>

<div id="content">
			
				<div id="inner-content" class="wrap clearfix">
			
				    <div id="main" class="eightcol first clearfix" role="main">
					
					    <article <?php post_class('clearfix'); ?> role="article">
						
						    <header class="article-header">
							
							    <h1 class="page-title">Contributors</h1>
                 
						
						    </header> <!-- end article header -->
					
						    <section class="entry-content">

<h2 class="small-subhead">Issue 9</h2>


 <p class="contributors"><strong>Larissa Shmailo’s</strong> work has appeared or is forthcoming in <em>Gargoyle, Barrow Street, Drunken Boat, Fulcrum, Rattapallax, Jacket, The Unbearables Big Book of Sex</em>, and the Penguin anthology <em>Words for the Wedding</em>. Her books of poetry are <em>In Paran</em> (BlazeVOX [books]), the chapbook <em>A Cure for Suicide</em> (Cervena Barva Press, with foreword by Philip Nikolayev), and the e-book <em>Fib Sequence</em> (Argotist Ebooks). Larissa recently won honorable mention in the international Russian literary translator’s competition for the Compass Award sponsored by Princeton University; her original translation of A. Kruchenych’s “Victory over the Sun” is archived at the Museum of Modern Art (MoMA), the Los Angeles County Museum of Art, and the Smithsonian, and may be read at the <em>Brooklyn Rail’s</em> InTranslation site: http://intranslation.brooklynrail.org/russian/victory-over-the-sun. She blogs at http://larissashmailo.blogspot.com/.</p>
    <p class="contributors"><strong>Susan Scutti</strong> grew up in Woodbridge, NJ and has lived in NYC since the late ’80s. She writes poems, stories and novels. Most recently, Paper Kite Press published her full-length poetry collection, <em>The Commute,</em> and Ravenrock Press published her novel, <em>The Deceptive Smiles of Bredmeyer Deed</em> (with artwork by Sarah Valeri).</p>
    <p class="contributors"><strong>Samuel Ray Delany,  Jr.</strong>, also known as Chip, is an American author, professor and literary critic. His work includes a number of novels, many in the science fiction genre, as well as memoir, criticism, and essays on sexuality and society. He has published several autobiographical and semiautobiographical accounts of his life as a black, gay, and highly dyslexic writer, including his Hugo Award–winning autobiography, <em>The Motion of Light in Water</em>. In one of his nonfiction books, <em>Times Square Red, Times Square Blue</em> (1999), he draws on personal experience to examine the relationship between the effort to redevelop Times Square and the public sex lives of working-class men, gay and straight, in New York City. The later novels <em>The Mad Man, Hogg</em> and <em>Phallos</em> can be considered pornography, a label Delany himself endorses. <em>The Mad Man</em> and <em>Phallos</em> are linked with his 2012 novel, <em>Through the Valley of the Nest of Spiders</em>, his most recent book. His science fiction novels include <em>Babel-17, The Einstein Intersection, Nova, Dhalgren,</em> and the <em>Return to Nevèrÿon</em> series. After winning four Nebula Awards and two Hugo Awards over the course of his career, Delany was inducted into the Science Fiction Hall of Fame in 2002. Between 1988 and 1999, he was a professor of comparative literature at the University of Massachusetts Amherst. Between 1999 and 2000, he was a professor of English at SUNY Buffalo. Since January 2001 he has been a professor of English and creative writing at Temple University in Philadelphia, where he is director of the graduate creative writing program.</p>
    <p class="contributors"><strong>Anna Mockler’s</strong> story collection <em>Burning Salt</em> (StringTown Press) was published in 2004. Her fiction has appeared in <em>Brooklyn Rail, Exquisite Corpse, Crab Creek Review, Raven Chronicles, Dial, Smoking Poet, Oxygen</em> and <em>Point No Point</em>. Other fiction was included in <em>The Unbearables Big Book of Sex</em> (2011, Unbearable Books/Autonomedia), <em>The Worst Book I Ever Read </em>(2009, <em>ibid</em>.), <em>Wreckage of Reason: Anthology of XXperimental Prose by Women Writers</em> (2008, Spuyten Duyvil) and <em>Dogs Cats Crows</em> (2001, Black Heron). She was born in New York and has lived all over the country, where she performed the traditional jobs of a writer: factory worker, office temp, waitress, printer, cabdriver, and restoration ecologist. She lives in Brooklyn.</p>
    <p class="contributors"><strong>Jesús Ángel García</strong> is a writer, musician and filmmaker based in San Francisco. “Sodomy Is a Threat to National Security: Fourth of July Weekend in Gethsemane” is adapted from his debut novel <em>badbadbad</em> (New Pulp Press). García is one-third of Three Times Bad, a dirty American roots-music string trio spunoff from the book’s original soundtrack. The band plans to release its first album after the end of the world in the summer of 2013. The <em>badbadbad</em> documentary film—based on the novel’s themes of fear, hypocrisy, intimacy in electronic culture, sexual morality and self-destruction—was an Official Selection of the 2012 Indie Fest USA International Film Festival. You can find all things 3xbad at: badbadbad.net and threetimesbad.com.</p>
    <p class="contributors"><strong>Amman Sabet</strong> is a designer and writer who vacillates between San Francisco and New York. He has published a smattering of poetry and cultivates a mattress novel in earnest, but won’t quit his day job (whatever that is).</p>
    <p class="contributors">Throughout the ’80s and ’90s, <strong>John Lurie</strong> led the legendary band the Lounge Lizards. He recorded 22 albums and the soundtracks for over 20 films, including <em>Get Shorty</em>, which earned him a Grammy nomination. As an actor, he had starring roles in the Jim Jarmusch films, <em>Stranger than Paradise</em> and <em>Down by Law</em>, and supporting roles in Wim Wenders’ <em>Paris, Texas</em>; Martin Scorsese’s <em>The Last Temptation of Christ</em> and David Lynch’s <em>Wild at Heart</em>, as well as a regular role on the HBO series <em>Oz</em>. Lurie wrote, directed and starred in the critically acclaimed television series, <em>Fishing with John</em>. For over thirty years, Lurie has been drawing and painting, yet only in the last eight years has he chosen to exhibit his work. In 2004, Lurie had his first painting exhibition at Anton Kern Gallery, New York. The Museum of Modern Art in New York and the Wadsworth Atheneum in Connecticut have acquired his work for their permanent collections. Lurie has published two collections of his work: <em>Learn to Draw</em>, a compilation of black and white drawings, and <em>A Fine Example of Art</em>, a full-color collection of over 80 reproductions.</p>
    <p class="contributors"><strong>Fred Frith</strong> is a songwriter, composer, improviser and multi-instrumentalist best known for the reinvention of the electric guitar that began with his solo album <em>Guitar Solos</em> in 1974. He learned his craft as both improviser and composer playing in rock bands, notably Henry Cow, and creating music in the recording studio. Much of his compositional output has been commissioned by choreographers and filmmakers, but his work has also been performed by Ensemble Modern, Hieronymus Firebrain, Arditti Quartet, Ground Zero, Robert Wyatt, Bang on a Can All Stars, Concerto Köln, and Rova Sax Quartet, among many others. He continues to perform internationally, most recently with Lotte Anker, Evelyn Glennie, Chris Cutler, John Zorn, Eye to Ear (a septet performing selections from his film music) and his latest band, Cosa Brava, whose most recent CD, <em>The Letter</em>, was released in 2012 to critical acclaim. Fred is the subject of Nicolas Humbert and Werner Penzels’ award-winning documentary film, <em>Step Across the Border.</em> For the latest news and information about him, visit www.fredfrith.com</p>
    <p class="contributors"><strong>Doug Rice</strong> is the author of the forthcoming <em>Between Appear and Disappear</em> as well as <em>Dream Memoirs of a Fabulist, Blood of Mugwump, Skin Prayer</em> and <em>A Good Cuntboy Is Hard to Find</em>. His work has appeared in numerous anthologies and journals. He is currently an artist-in-residence at Akademie Schloss Solitude, in Stuttgart, and teaches at Sacramento State University.</p>
    <p class="contributors"><strong>Bradley Spinelli </strong>has herded cattle, worked on Wall Street and run away with the circus. His novel, <em>Pirate’s Alley,</em> was a semifinalist in the Faulkner Competition. His play <em>Elusive</em> was presented by the National New Playwrights Network in Denver and received a staged reading at 13th Street Rep (NYC). His short fiction has been published by Sparkle Street and by Le Chat Noir (“Eyes of DeLillo<em>,</em>” 2010), which also published an excerpt from the novel, <em>Killing Williamsburg,</em> in the collection <em>Drinking with Papa Legba</em> (2011). He lives with his wife in Brooklyn.</p>
    <p class="contributors"><strong>Marty Thau</strong> attended New York University from 1956 to 1960 and studied communication arts. After spending the latter half of the ’60s as an award-winning record industry executive (Cameo-Parkway and Buddah Records), Thau forsook a cushy position with a mainstream production company (Van Morrison, John Cale, Miriam Makeba) to manage the rebirth of rock &amp; roll in the form of the New York Dolls in the early ’70s. Thau was integral to the development of New York’s underground rock demimonde that evolved into a spawning ground of punk and new wave stars, and he is acknowledged as such in the <em>Encyclopedia of Record Producers,</em> a reference book that deals with the behind-the-scenes heroes of popular music. He worked with the Ramones, Blondie, Brian Setzer and Richard Hell, and produced Suicide, the Real Kids, the Fleshtones, and Martin Rev for his Red Star Label. These days, his time is spent licensing his music and writing his memoir. He was born and raised in NYC and now lives in Virginia near his daughter Leslie and two grandsons.</p>
    <p class="contributors"><strong>Jenny Wade</strong> is a musician (previous bands include Rude Buddha, Vodka, Swans, Timber) and has a Master’s Degree in Russian Literature from Columbia University. She likes to translate the great Russian poets in the morning while having her tea. She lives with her husband and two daughters in California’s Bay Area.</p>
    <p class="contributors"><strong>Chris Bava</strong> is an American photographer who lived and worked in Tijauana, Mexico. He was a former heroin trafficker who served 8 years in Federal prison following a worldwide sting operation in the late 1980s. Chris also struggled with addiction before and after his stint in prison, which eventually motivated him to move to Tijuana, to seek out alternative cures. You can learn more about Chris and his fascinating life and work by watching a feature-length documentary, produced as part of the Exile Nation Project<em>, </em>available at: http://vimeo.com/38354777.</p>
    <p class="contributors"><strong>J.D. King</strong> is a graphic artist, experimental musician and writer living in upstate NY. Recent illustration clients include <em>The New York Times, The</em> <em>Boston Globe, </em>the US Postal Service, <em>Audubon Magazine, The Washington Post, The Baffler,</em> and <em>P.I.M</em>. His band, J.D. King &amp; The Coachmen, have two high-energy avant-rock albums out on Ecstatic Peace.</p>
    <p class="contributors"><strong>James Romberger</strong> is an American fine artist and cartoonist known for his depictions of New York City’s Lower East Side. Romberger’s pastel drawings of the ravaged landscape of the Lower East Side and its citizens are in many public and private collections, including the Metropolitan Museum of Art and Brooklyn Museum. For a long time, Romberger has been contributing work in the comics medium, including <em>Seven Miles A Second</em>, Romberger and Marguerite Van Cook’s collaboration with artist, writer, and AIDS activist, David Wojnarowicz. Romberger is also a critic and writer for <em>Publisher’s Weekly</em> and the comics blog the <em>Hooded Utilitarian</em>.</p>
    <p class="contributors"><strong>Ghazi Barakat</strong> is a German-Palestinian musician, journalist and subversive-art aficionado living in Berlin. He is currently making meta music for meta people in a meta world under the monicker of Pharoah Chromium and testing toxins from cold-blooded animal species for the “new drug revolution.”</p>

<h2 class="small-subhead">Issue 8</h2>

    <p class="contributors">
    <strong><a href="http://www.geocities.com/pagan_pages/" title="Mike Hudson" target="_blank">Mike Hudson</a>,</strong> founder and lead singer of seminal seventies punk rock band the Pagans, has spent the past 35 years working for different magazines and newspapers, writing mostly journalism, criticism and essays but a small stream of fiction as well. He recently published <em>Never Trust the World</em>, his fifth book. In 2011, he had a nationwide booktour along with Bob Pfeiffer of Human Switchboard, David Thomas of Pere Ubu and Cheetah Chrome of the Dead Boys, all ex–punk rockers from Cleveland who have since become authors.
</p>
<p class="contributors">
    <strong>Karen Lillis</strong> is the author of four books of fiction, most recently <em>Watch the Doors as They Close</em> (Spuyten Duyvil, February 2012). She is currently working on a memoir called <em>Bagging the Beats at Midnight</em>, about her years behind the counter at St Mark’s Bookshop. She blogs at <a href="http://karenslibraryblog.blogspot.com" title="Karen the Small Press Librarian" target="_blank">Karen the Small Press Librarian</a>.
</p>
<p class="contributors">
    <strong>Jim Feast</strong> is the author (with Ron Kolm) of the novel <em>Neo Phobe</em>, and with Gary Null of the health book <em>Germs, Biological Warfare and Vaccinations: What You Need to Know</em>. He is a member of the <a href="http://unbearables.com" title="Unbearables" target="_blank">Unbearables</a> writers group.
</p>
<p class="contributors">
    <strong>Chavisa Woods</strong> is a Brooklyn-based author whose work focuses on issues of class, culture, gender, and sexuality. She is the recipient of the 2009 Jerome Foundation Award for emerging writers. Her debut collection of short stories, <em>Love Does Not Make Me Gentle or Kind</em> (Fly By Night Press, 2009) was a Lambda Literary Award finalist for Debut Fiction. Woods recently completed her second work of fiction, <em>The Albino Album</em>, a novel, which is set to be released by Seven Stories Press in the Spring of 2013. Woods’ poetry, short stories and essays have been published nationally and internationally in a number of magazines and journals, including the <em>New York Quarterly</em>, <em>The Evergreen Review</em>, and <em>Union Station</em>.
</p>
<p class="contributors">
    <strong><a href="http://www.jamesgreer.net/" target="_blank">James Greer</a></strong> is the author of the novels <em>Artificial Light</em> (LHotB/Akashic 2006) and <em>The Failure</em> (Akashic 2010), and the non-fiction book <em>Guided By Voices: A Brief History</em>, a biography of a band for which he played bass guitar. He’s written or co-written movies for Lindsay Lohan, Jackie Chan, and Steven Soderbergh, among others. He is a Contributing Editor for the <em>Los Angeles Review of Books</em>.
</p>
<p class="contributors">
    <strong><a href="http://gleefarm.blogspot.com" title="Glee Farm" target="_blank">Todd Colby</a></strong> has published four books of poetry: <em>Ripsnort, Cush, Riot in the Charm Factory: New and Selected Writings,</em> and <em>Tremble &amp; Shine</em>, all published by Soft Skull Press. Colby, also a visual artist and performer, has been broadcast nationally on PBS, MTV and NPR for Garrison Keillor’s <em>Writer’s Almanac</em>. He was the lead singer for the critically acclaimed band Drunken Boat. Todd is a frequent collaborator with artist Marianne Vitale and art collective Kunstverein. His books and paintings with the artist David Lantow can be seen in the Brooklyn Museum of Art and The Museum of Modern Art special collections libraries. Colby serves on the Board of Directors for The Poetry Project, where he teaches poetry workshops. He also serves on the Editorial Board of <em>LungFull! Magazine</em> and is a contributing editor for <em>Cousin Corrine’s Reminder</em>.
</p>
<p class="contributors">
    <strong><a href="http://www.subyron.com" target="_blank">Su Byron</a></strong> is a poet and freelance writer living in Sarasota, Florida. Her poetry and short stories have been published in numerous anthologies and magazines. She is currently working on two new collections of poems, <em>Fire Burns Less Than This</em> and <em>Lying in a Filthy Bed with a Dying Cat</em>. She works as a freelance writer and editor to earn her daily dose of wine and bread.
</p>
<p class="contributors">
    <strong>Les Bridges</strong> says: “It was, it was a heady mix of fabulous cash and crazy ideas. I lived on planes&nbsp;.&nbsp;.&nbsp;.&nbsp;LA, Chicago&nbsp;.&nbsp;.&nbsp;.&nbsp;then in a great house in the East Village. My life was a fireball. Cannot this do forever, right? The stroke was a massive thunderbolt.”
</p>
<p class="contributors">
    <strong>William Lessard’s</strong> work has appeared in <em>Maintenant 6</em>, an international journal of Dada and other literary hijinks. He’s also a fan of the New York Mets.
</p>
<p class="contributors">
    <strong><a href="http://urbgraffiti.wordpress.com/" target="_blank">Mark McCawley</a></strong> is the author of a collection of poetry, <em>Voices from Earth</em>, and eight chapbooks, including <em>Stories for People with Brief Attention Spans</em> and <em>Just Another Asshole: Short Stories</em>. His fiction has appeared in anthologies such as <em>Burning Ambitions:The Anthology of Short-Shorts, Grunt &amp; Groan: The New Fiction Anthology of Work and Sex</em> and <em>Front &amp; Centre #9</em>.
</p>
<p class="contributors">
    <strong>Rob Hardin</strong> is the author of <em>Distorture</em>, a callously florid collection of short stories that seduced the Firecracker Award into being won and then told the award it should really start seeing other people. His fiction and essays have manipulated their way into the anthologies <em>Avant-Pop: Fiction for a Daydream Nation</em>, <em>Postmodern Culture</em>, <em>Storming the Reality Studio: A Casebook of Cyberpunk &amp; Postmodern Science Fiction</em>, <em>In the Slipstream, Forbidden Acts</em>, <em>Mississippi Review</em> and <em>An Exaltation of Forms</em>. As a studio musician, he has intimidated others into using him on more than forty albums.
</p>
<p class="contributors">
    <strong>Ray Jicha</strong> was born in Cleveland, OH and grew up in South Carolina. A frequent traveler and occasional scholar, he found youthful purpose in fronting microcosmic rock bands. Since relocating to Portlandia in 1999 he has learned to miss the South, but not much. His novella, <em>Requiem for a Cornerman</em>, is now available.
</p>
<p class="contributors">
    <strong>Tom McGlynn</strong> is an artist, writer, and independent curator based in the NYC area. His work is represented in many national and international collections, including the permanent collections of the Whitney Museum, The Museum of Modern Art, and The Cooper-Hewitt National Design Museum of the Smithsonian. His art has been reproduced on the cover of <em>Artforum</em> magazine and featured in articles in <em>The New York Times</em>. Mr. McGlynn has taught as an Assistant Professor at Castleton State College, Vermont, and has previously been a Visiting Artist Lecturer at the Mason Gross School of Fine Arts at Rutgers University, NJ.
</p>
<p class="contributors">
    <strong>Ruby Ray</strong> got her start as staff photographer and muse at seminal punk culture rag, <em>Search &amp; Destroy Magazine</em>, and co-founded <em>Re/Search Publications</em>; her iconic Burroughs photo graced the cover of issue 4/5. Ray’s historic documentation of California’s 1970s and 1980s underground music and art scene provides a rare insider’s look at this pivotal time in musical history. A new hardback book, <em>From the Edge of the World, California Punk 77-81</em>, will be published in the Fall of 2012 and her Ebook is going to go live any day now on <a href="http://www.amusedom.com" title="Amusedom" target="_blank">Amusedom</a>.
</p>
<p class="contributors">
    <strong><a href="http://www.posi-tone.com/newmonsters/newmonsters.html" target="_blank">The New Monsters</a></strong> are <a href="http://www.plonsey.com/" target="_blank">Dan Plonsey</a> (tenor sax), <a href="http://www.thecodeinternational.com/site/" target="_blank">Steve Horowitz</a> (bass), Jim Bove (drums), Steve Adams (flute, soprano sax and alto sax) and Scott Looney (piano). They perform compositions by Dan Plonsey.
</p>
<p class="contributors">
    <a href="http://www.thaddeusrutkowski.com" target="_blank"><strong>Thaddeus Rutkowski</strong></a> is the author of the innovative novels <em>Haywire, Tetched</em> and <em>Roughhouse</em>. He teaches literature at City University of New York and fiction writing at the Writer’s Voice of the West Side YMCA in Manhattan.
</p>
<p class="contributors">
    After a decade and a half spent in Chicago, where she wrote freelance and served as a founding contributing editor of a magazine about digital photography, <strong>Jennifer Adams</strong> moved to New York to be closer to The Strand. Her first book, based on her blog <a href="http://TheBooksTheyGaveMe.com" title="The Books They Gave Me" target="_blank">TheBooksTheyGaveMe.com</a>, will be published by Free Press in early 2013. She is at work on a variety of fiction projects, including a zombie novel for kids, and she blogs sporadically at <a href="http://jen-adams.com" target="_blank">jen-adams.com</a>. She lives in Astoria, New York and is the mother of two boys.
</p>
<p class="contributors">
    <strong>James Romberger</strong> is an American fine artist and cartoonist known for his depictions of New York City’s Lower East Side. Romberger’s pastel drawings of the ravaged landscape of the Lower East Side and its citizens are in many public and private collections, including the Metropolitan Museum of Art and Brooklyn Museums. His solo and collaborative exhibitions have appeared at Ground Zero Gallery NY, the Grace Borgenicht Gallery, Gracie Mansion, The Proposition and the New Museum of Contemporary Art. Romberger has long contributed work in the comics medium to alternative publications such as <em>World War 3 Illustrated</em>. <em>Ground Zero</em>, his science-fiction strip collaboration with his wife, filmmaker Marguerite Van Cook, was serialized through the 1980s and 1990s in various downtown literary magazines. <em>Seven Miles A Second</em>, Romberger and Van Cook’s graphic novel done in collaboration with artist, writer, and AIDS activist David Wojnarowicz.Romberger is also a critic and writer for <em>Publisher’s Weekly</em> and the comics blog the Hooded Utilitarian.
</p>
<p class="contributors">
    <strong>Justine Frischmann</strong> is an artist and musician who has performed and exhibited in Europe, North America, Japan and Australia. She wrote and performed with Elastica and, more recently, has written and produced for a number of artists including M.I.A. She has a degree in architecture from University College London, has studied Contemplative Art at Naropa University, and Fine Art at the San Francisco Art Institute. Her work has been reviewed in many publications including the <em>London Sunday Times</em> (Art and Culture), the <em>LA Times</em>, and the <em>London Telegraph</em>. She was a presenter and writer on <em>The South Bank Show</em>, the UK’s oldest and most respected arts program, and has presented programs on art, music and architecture for BBC TV, BBC World TV (Arts), and BBC Radio 6. She has written about art and culture for magazines such as <em>ID</em> and <em>The Face</em> (UK), and was a judge for the Sterling Prize. She now lives and works in the Bay Area.
</p>
<p class="contributors">
    Additional art by <a href="http://spirer.com" title="Jeff Spirer" target="_blank">Jeff Spirer</a>, Chris Bava, <a href="http://www.cedricmonot.com/ title="Cédric Monot" target="_blank">Cédric Monot</a>, Kym Ghee, Marcin Owczarek, <a href="http://www.swipple.com/davidwest" title = "David West" target="_blank">David West</a>, <a href="http://www.charliehomo.com/" title="Charlie Homo" target="_blank">Charlie Homo</a>, Leslie Hardie and <a href="http://tedbarron.com/photo.html" title="Ted Barron" target="_blank">Ted Barron</a>.
</p>
<h2 class="small-subhead">Issue 7</h2>

    <p class="contributors"><strong><a href="http://www.diremccain.com" title="Dire McCain" target="_blank">Díre McCain</a></strong> is a five-dimensional creature who fell through a Lorentzian traversable wormhole into a three-dimensional universe, landing on what was, at the time, the second rock from the Sun. After a nebulous sojourn in the Zone of Avoidance, while trapped in a self-induced state of suspended animation, McCain was unwittingly converted into a transportable energy pattern and ultimately rematerialized on 21st century Earth. McCain “suffers from” Aboulomania, Planomania, Eleutheromania, Habromania, Hydrodipsomania, a severe case of Logomania, and innocuous Daddy Issues; possesses a ridiculous number of utterly useless skills, including the mythical mantic Seventh Sense, which is merely another of myriad delusional beliefs; and is co-founder and co-editor of  <a href="http://www.paraphiliamagazine.com" title="Paraphilia Magazine" target="_blank">Paraphilia Magazine</a> & Books.

    <p class="contributors"><strong><a href="http://www.robroberge.com" title="Rob Roberge" target="_blank">Rob Roberge</a></strong> is the author of the upcoming book of stories <em>Working Backwards from the Worst Moment of My Life</em> and the neo-noir novels <em>More Than They Could Chew</em> (Perennial Dark Alley/Harper Collins, February 2005) and <em>Drive</em> (re-issue, Hollyridge Press, 2006). His stories have been featured in <em>ZYZZYVA, Chelsea, Other Voices, Alaska Quarterly Review</em>, and the “Ten Writers Worth Knowing Issue” of The <em>Literary Review</em>. In his spare time, he plays guitar and sings with Los Angeles area garage/punk bands the Violet Rays, the Danbury Shakes and LA’s legendary punk pioneers, the Urinals.

    <p class="contributors"><strong><a href="http://cityofstrangers.net" title="City of Strangers" target="_blank">City of Strangers</a></strong> writes about NYC and related subjects.

    <p class="contributors">English-born <strong>Marguerite Van Cook</strong> came to New York with the punk band the Innocents, after touring with the Clash. She stayed and opened a gallery, Ground Zero, with James Romberger, where showed her own and others’ art. She has enjoyed a varied career in the arts as a painter, writer, poet, and multimedia artist. She collaborated on the ground-breaking graphic novel, <em>Seven Miles a Second</em>, which was included in the Museum of Modern Art’s Millennium Show, with Romberger and David Wojnarowicz. Van Cook both makes and acts in films,, and her work is in many major galleries and collections. She holds an M.A in Modern European studies from Columbia University and is currently enrolled in a French PhD program.

    <p class="contributors"><strong>Mark Netter</strong> has spent too much time both in and out of Hollywood wasting a perfectly good NYU grad film school education in the television, movie, videogame, entertainment advertising and social media industries. He bought his first guitar, a Tele, and taught himself how to play in early 2010 in order to write the songs for his “Little Punks” screenplay (done). He tends to trust people he meets from upstate New York, where he was raised, because in those winters you really learn the meaning of friendship. After living in Providence, London, NYC, LA and SF, he makes his home in Santa Monica with his wife and two rambunctious boys he likes to take to the movies, especially revivals. He has been told he looks like both Lou Reed and Elvis Costello in the past, more recently, the dad from <em>Modern Family</em>.

    <p class="contributors">Guitarist <strong>Michael LaMacchia</strong> was born in Kenosha Wisconsin, than moved to San Francisco at 18 and began his musical career. <strong>Niels Myrner</strong> (drums), a San Francisco native, currently lives with his wife Yvette in Mill Valley, California where he performs, records and teaches full time. <strong>Dan Feiszli</strong> (bass) lives in the Bay Area where he records, tours and performs with a wide variety of artists.

    <p class="contributors"><strong>Drew Hubner</strong> is the author of <em>American by Blood: A Novel</em> and <em>We Pierce: A Novel</em>. His latest work, <em>East of Bowery</em> (with Ted Barron), will be published by Sensitive Skin Books in fall 2011. He lives in New York City with his wife Sarah and children Henry, August and Eleanor. He works as a Lecturer of English at Hostos Community College of the City University of New York.

    <p class="contributors"><strong><a href="http://www.myspace.com/johnshall" title="John S. Hall" target="_blank">John S. Hall</a></strong> is 99% vegan, 98% agnostic, 97% heterosexual, and not as delicious as he used to be. He’s the vocalist and lyricist of King Missile (Dog-Fly Religion). He works as an Intellectual Property Analyst at a big law firm, Sullivan and Cromwell. He supposes he is still a poet and is currently working on a memoir/novel.

    <p class="contributors"><strong>Erika Schickel</strong> is the author of <em>You’re Not the Boss of Me: Adventures of a Modern Mom</em>. Her essays, reviews and reporting have appeared in <em>The Los Angeles Times, The L.A. Weekly, L.A. City Beat</em> and <em>Bust Magazine</em>. She is currently working on a full-length memoir, <em>Unsupervised: A Love Story</em>.

    <p class="contributors"><strong><a href="http://www.janicesloane.com" title="Janice Sloane" target="_blank">Janice Sloane</a></strong> has shown her work in numerous group and single shows throughout the United States and Mexico. Her most recent exhibition, entitled “That’s It,” took place at Governor’s Island, NY, in 2011.

    <p class="contributors"><strong>Shalom Tomas Neuman</strong> was born in Prague, Czechoslovakia. He is the last surviving male of a large Jewish family, most of whom perished in Nazi Germany’s Holocaust. His family escaped from Prague toward the end of the war and emigrated to Haifa, Israel, where he spent the rest of his childhood. The family emigrated to the U.S. when he was 12 and he has lived there ever since, currently residing in New York City. He is the recipient of dual BFAs and MFAs in painting and sculpture from Carnegie-Mellon University, has dual residences and studios in both New York and Prague, and divides his time between the two. He currently teaches at Pratt Institute of Technology. In September 2011, his exhibit “Talking at You – Promlouvání,” premiered at the National Gallery in Prague.

    <p class="contributors">Under her former name, <strong>Diane Rochlin</strong>, Flame Schon co-directed and co-edited <em>Vali: The Witch of Positano</em>, a documentary about an Australian artist/shaman living in Italy that won the social documentary award at the Mannheim International Festival in 1966. Moving into video with a new Sony Portapak via a grant from the American Film Institute in 1969, she collaborated on videotaping The Living Theater’s historic final performance of “Paradise Now” at the Sportspalast in Berlin. <em>Dope</em>, a feature-length 16mm film (in collaboration with the late Sheldon Rochlin) on the London drug scene, premiered in 1975 in the First New American Cinema Series at the Whitney Museum. Since 1989, she has lived in Santa Fe, New Mexico, where she creates video and digital art.

    <p class="contributors"><strong>Michael Jon Fink</strong> is a composer/performer who resides in the San Fernando Valley just north of Los Angeles. For the last thirty years, he has served on the faculty of the Herb Albert School of Music at the California Institute of the Arts where he teaches Composition, Orchestration and Analysis.

    <p class="contributors">Additional art by <a href="http://spirer.com" title="Jeff Spirer" target="_blank">Jeff Spirer</a>, Chris Bava, Jim C, Sofles and Ted Barron.

<h2 class="small-subhead">Issue 6</h2>

    <p class="contributors"><strong>Carl Watson</strong> is a writer living in NYC. He has published some books including <em>Beneath the Empire of the Birds</em> (short stories) by Apathy Press, and <em>The Hotel of Irrevocable Acts</em> (a novel) by Autonomedia. These books have also been published in France by Vagabonde Press and Gallimard respectively. Recently Vagabonde has published Une Vie Psychosomatique.  Watson also writes regular opinionated essays (under several names) for <a href="http://www.williamsburgobserver.org/category/watson/" target="_blank">The Williamsburg Observer</a>, an anarchist publication that originated at the Right Bank Cafe in Brooklyn.  Currently he is working on a book about Henry Darger's autobiography which he hopes will dispel the myth of literature and romantic genius and condemn all writers to the category of biological machines engaged in redundant self-constitution no different than the growth of crystals, the birth of stars, or the splitting of amoeba. Watson drinks to get through his day.

    <p class="contributors"><strong><a href="http://bonny-finberg.blogspot.com/" target="_blank">Bonny Finberg</a></strong> has published fiction, personal essays, poetry, photographs and reviews. Her collection of short stories, “How the Discovery of Sugar Produced the Romantic Era” was published by Sisyphus Press, 2006 and was documented in the feature length video “5 GUYS READ FINBERG.” Publishers’ Weekly said of her work in Best American Erotica of 1996 (Simon & Schuster) that it "…exudes a stunning sensual sensibility." Her work has been translated into French, Hungarian and Japanese. She has been included in the Outlaw Bible of American Poetry (Thunder’s Mouth Press), as well as the anthologies Unbearables, Crimes of the Beats, Help Yourself and The Worst Book I Ever Read. (Autonomedia), Lost and Found: Stories from Mr. Beller's Neighborhood. Also, the "Love" issue of Van Gogh's Ear and Upstairs At Duroc, both published in Paris. She is a contributor to A Gathering of Tribes and Le Purple Journal. Her work has been aired on the radio in London and Amsterdam. She lives in Paris and New York.

    <p class="contributors"><strong><a href="http://www.maxblagg.net/" target="_blank">Max Blagg</a></strong> was born in England and has lived in New York City since 1971. He is the author of four collections of poetry, and other books. His most recent publication The Little Dress Book [Shallow Books, NYC 2010] was listed in About Poetry’s Top 20 small press publications of 2010. He has collaborated with various artists, including Alex Katz, Jack Pierson, Richard Prince and Keith Sonnier. With Glenn O’Brien Blagg co-edited the legendary art/lit/tit magazine, Bald Ego. He is a contributing editor to Oyster, BG and 10 Magazine and is on the faculty at the School of Visual Arts. A book of stories, Ticket Out, and new collection of poems, Slow Dazzle, are forthcoming.

    <p class="contributors"><strong><a href="http://www.fabulara.com/" target="_blank">Patricia Eakins</a></strong> is the author of <em>The Hungry Girls and Other Stories</em> and <em>The Marvelous Adventures of Pierre Baptiste</em>  (a novel) which won both the NYU Press Prize for Fiction and the Capricorn Fiction Award of the Writer’s Voice. She has also been awarded the Aga Khan Prize for Fiction from The Paris Review. She is currently working on a collection of stories.

    <p class="contributors">Composer, multi-instrumentalist, and producer <strong><a href="http://www.panix.com/~esharp/" target="_blank">Elliott Sharp</a></strong> has been a central figure in the experimental music scene in New York City for over thirty years and currently leads the projects Carbon, Orchestra Carbon, Tectonics, and Terraplane. He has pioneered techniques of applying fractal geometry, chaos theory, and genetic metaphors to musical composition and interaction and has collaborated with a diverse range of artists, including Ensemble Modern, Qawwali singer Nusrat Fateh Ali Khan, the Radio-Symphony of Frankfurt, pop singer Debbie Harry, computer artist Perry Hoberman, blues legends Hubert Sumlin and Pops Staples, jazz greats Jack deJohnette and Sonny Sharrock, andconceptual artists Pierre Huyghe and Christian Marclay.  Sharp's work has been featured at festivals worldwide, including the 2008 New Music Stockholm festival, the 2007 Hessischer Rundfunk Klangbiennale, and the 2003 and 2006 Venice Biennales.  He has composed for video artists Nam June Paik and Paul Garrin and for filmmakers Toni Dove, Jonathan Berman, and Illppo Pohjola.  His sci-fi opera for teenage performers which he also wrote and directed, "About Us" was commissioned by the Bayerische Staatsoper in Munich and premiered in July 2010.  Sharp's work is the subject of a documentary, "Doing The Don't" by Bert Shapiro.

    <p class="contributors"><strong>jennifer jazz</strong> was the lead singer of the eighties East Village bands, the Guerilla Girls and Pleasure. In 1996, she played the role of Virginia in the B movie, Rescuing Desire. Her short film, Je m'ennuie was featured at the 2010 UAMO Festival in Munich http://youtu.be/XSMdPn3xxEg. Excerpts of her untitled memoir-in-progress have appeared in Makeshift and The International Review of African-American Art.

    <p class="contributors"><strong>Sean Flaherty</strong> has been writing poems about Brooklyn and commuting on the subway since 1989.  He has self-published works such as Cannibal Love: No Regrets (ca.1991) and Skinny White Beer Machine (ca. 1994) by having multiple artists bind the books which were then included in shows at locations such as Kelly Lamb's Thicket Gallery and The National Arts Club.  His work has appeared on Green Spot Blue once a week since December 2010.   Currently Green Spot Blue is running all 55 of his subway pomes, once a week, including a brief <a href="http://www.greenspotblue.com/world/2011/5/18/a-brief-introduction-to-subway-pomes.html" target="_blank">introduction to the series</a>.

    <p class="contributors"><a href="http://www.swipple.com/davidwest" target="_blank"><strong>David West</strong></a> is an American artist who habits Paris.   He's lived in New York for long stretches of time, as well as San Francisco and Chicago.

    <p class="contributors"><strong><a href="http://www.imdb.com/name/nm0706268/" target="_blank">Kevin Rafferty</a></strong> is an American documentary film cinematographer, director, and producer, best known for his 1982 documentary The Atomic Cafe. Rafferty studied architecture at Harvard and film at the California Institute of the Arts. He helped teach the craft of filmmaking to Michael Moore during the production of <em>Roger & Me</em> in 1989.  He is the director, producer, editor and cinematographer of many documentary projects, including <em>Blood in the Face</em>, <em>The War Room</em>, <em>Feed</em>, and <em>The Last Cigarette</em>. His latest project is <em>Harvard Beats Yale 29-29</em>.

    <p class="contributors"><strong>John Griffin Morrissey's</strong> current work is focused on the art, mood, and history that is so rich in Greenwood Cemetery. Aside from his painting, Morrissey has worked as a photo editor, punk rock drummer, and motorcycle mechanic for most of his life.  He married his high school sweetheart at the age of 57.

    <p class="contributors"><strong><a href="http://www.sparklestreet.com/MikeDecapite.html" target="_blank">Mike DeCapite</a></strong>'s first novel, <em>Through the Windshield</em>, was published by Sparkle Street Books in 1998. His story "Sitting Pretty" came out as a CUZ Edition in 1999 and was included in The Italian American Reader (Wm. Morrow 2003; HarperCollins 2005). During 2003 and 2004 he wrote a monthly column called Radiant Fog for angle magazine. "Love" is taken from RUINED FOR LIFE!, an unpublished novel. He and Ted Barron, who took the photograph that's the subject of the piece, are old friends and periodic collaborators. DeCapite lives in Brooklyn. More about him, including new work, can be found at www.sparklestreet.com.

    <p class="contributors">With additional art and commentary by <a href="http://charliehomo.com/" target="_blank">Charlie Homo</a>, <a href="http://spirer.com/" target="_blank">Jeff Spirer</a>, <a href="http://www.cedricmonot.com/all.htm" target="_blank">Cedric Monot</a>, Hal Hirshorn, <a href="http://tedbarron.com/" target="_blank">Ted Barron</a>, <a href="www.flickr.com/lauralionn" target="_blank">Laura Ann Morrison</a>, Marguerite Van Cook and S. A. Emmons.

<h2 class="small-subhead">Issue 5</h2>

<p class="contributors"><a href="http://www.johannaellen.dinstudio.co.uk/" target="_blank"><strong>Jóhanna Ellen</strong></a> (born 1983 in Höfn í Hornafirði, Iceland), is currently studying for her BFA at the Art Academy in Trondheim, Norway.

<p class="contributors"><a href="http://admissions.tumblr.com/" target="_blank"><strong>Jennifer Adams</strong></a> recently abandoned Chicago and moved to New York, where, she heard, there is a shortage of fiction writers. Nevertheless, she continues to read and write from her drafty garrett in Astoria.

<p class="contributors"><a href="http://www.scabvendor.com/" target="_blank"><strong>Jonathan Shaw</strong></a> is a world-traveling outlaw artist, gonzo war-correspondant, novelist, blogger, head doctor, anti-folk hero and whorehouse philosopher. A legendary tattoo master and notorious creator of trendsetting underground art, Shaw is the author of <em>Narcisa: Our Lady of Ashes</em>, soon to be re-released, <em>Love Songs to the Dead</em>, and is currently working on <em>Scab Vendor: A Novel</em>. His advice column, <a href="http://scabvendor.tumblr.com/" target="_blank">Dear Scabby</a>, is a must-read for the lovelorn, forsaken and just plain bored. Jonathan currently resides in Rio De Janiero, Brazil.

<p class="contributors"><strong>Melissa Febos</strong> is the author of <a href="http://www.amazon.com/gp/product/B004A14WAO?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=B004A14WAO">Whip Smart: A Memoir</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=B004A14WAO" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />. Her writing has been published in <em>The Southeast Review</em>,<em> Redivider, Dissent, The Chronicle of Higher Education Review</em>, and <em>Bitch Magazine</em>, among many others, and she has been profiled in venues ranging from the cover of the <em>NY Post</em> to NPR’s Fresh Air. A MacDowell Colony fellow, She teaches at Purchase College, Sarah Lawrence, The New School, and NYU, and holds an MFA from Sarah Lawrence. She resides in Brooklyn, and is currently at work on a novel.

<p class="contributors"><strong>D. Scot Miller</strong> is a commissioned San Francisco writer, visual artist , teacher, curator. He sits on the board of directors of nocturnes review, and is a regular contributor to The East Bay Express, San Francisco Bay Guardian, PopAfricana, and Mosaic Magazine. He is completing a book of poems, his Afro-surreal novel, Knot Frum Hear, and  is manifesting his old fashioned manifesto: This Is AfroSurreal!

<p class="contributors"><strong><a href="http://www.facebook.com/pages/Portrait-paintings-by-Samoa/123813264344039" target="_blank">Samoa Moriki</a></strong> was born in small fishing town in Hiroshima, Japan. He was a vital part of art movement in downtown New York City since early 80s'. Also known as co-founder and guitarist of legendary rock band, "The Voluptuous Horror of Karen Black". He currently performs with the country-western band The Lonely Samoans and is available for portraits by commission.

<p class="contributors"><strong>steve dalachinsky</strong> was born in brooklyn shortly after the last BIG WAR and has managed to survive lots of little wars. his work has appeared in journals both on and off line. he has many books, chapbooks and cds the latest being <em>Mantis</em> from Iniquity Press, <em>Reaching Into the Unknown </em>(Roguart) and the Pen Award-winning <em>Final Nite</em> from Ugly Duckling Presse. he`s never happy about anything and both envies and despises those in academia as well as everyone else.


<p class="contributors"><a href="http://www.lynlifshin.com" target="_blank"><strong>Lyn Lifshin</strong></a> has written more than 125 books including the Paterson Poetry Award winner <em>Before It's Light</em> and the Jack Kerouac Award winner <em>Kiss The Skin Off</em>. Her poems have appeared in most poetry and literary magazines in the U.S.A, and her work has been included in virtually every major anthology of recent writing by women. She has given more than 700 readings across the U.S.A. and has taught poetry and prose writing for many years at universities, colleges and high schools, and has been Poet in Residence at the University of Rochester, Antioch, and Colorado Mountain College. Winner of numerous awards including , Lyn is the subject of the documentary film <em>Lyn Lifshin: Not Made of Glass</em>.

<p class="contributors"><a href="http://mindhoney.com/" target="_blank"><strong>Wanda Phipps</strong></a> is a writer/performer living in NYC.  Her publications and recordings include <a href="http://www.amazon.com/Field-Wanting-Wanda-Phipps/dp/1934289604/ref=sr_1_2?ie=UTF8&amp;s=books&amp;qid=1207705068&amp;sr=1-2" target="Top">Field of Wanting: Poems of Desire</a>, <a href="http://www.amazon.com/exec/obidos/ASIN/193236031X/ref=rm_item" target="Top">Wake-Up Calls: 66 Morning Poems</a>, and the CD-Rom <a href="http://www.fauxpress.com/b/ph.htm" target="Top">Zither Mood</a>. Her poetry has been translated into Ukrainian, Hungarian, Arabic and Galician. She has received awards from the New York Foundation for the Arts, the National Theater Translation Fund, and others. As a founding member of <a href="http://www.brama.com/yara/ " target="Top">Yara Arts Group</a> she has collaborated on numerous theatrical productions presented in Ukraine, Kyrgyzstan, Siberia, and at La MaMa, E.T.C. in NYC.  She’s curated reading series at the Poetry Project at St. Mark's Church and written about the arts for Time Out New York, Paper Magazine, and About.com.

<p class="contributors"><strong>Norman Douglas</strong> was one of the original editors of Peau Sensible. He currently lives in Hudson, NY. You can find his musings and podcasts over at <a href="http://www.thing.net/~vibekeie/ie.htm" target="_blank">Individual Electric</a>.

<p class="contributors"><strong>Timber</strong> was <a href="http://www.myspace.com/rbrownout" target="_blank">Rick Brown</a>, Mark Howell and Jenny Wade. Rick lives in NY and still plays music with both Sue Garner (Two Mule Team) and Mark Howell (Inconvenient Music). Mark got a Ph.D. in Ethnomusicology (from the CUNY grad ctre.) and now runs an archaeology park and museum in the Mississippi Delta, Winterville Mounds. Jenny Wade lives in the San Francisco Bay Area and has recently picked up the bass after a long respite - she's interested in finding folks to jam with - drop us a line here at Sensitive Skin and we'll put you in touch if you're interested!

<h2 class="small-subhead">Issue 4</h2>
<p class="contributors"><a href="http://www.akroncracker.com/" target="blank"><strong>Ralph Carney</strong></a> is a multi-instrumentalist/horn player who has spent the better part of the last 2 decades criss-crossing the world, on stage and in studios with the likes of Tom Waits, Jonathan Richman, William Burroughs, Allen Ginsberg, B-52’s, Marc Ribot, Bill Laswell, David Thomas, Hal Wilner, Elvis Costello, Tipsy, Galaxie 500, Daevid Allen, Mushroom, Oranj Symphonette and The Black Keys, to name a few.

<p class="contributors"><strong>Jill Rapaport</strong> is a writer of fiction and nonfiction prose, plays, essays, poems and songs. Her work has been published in a number of literary magazines and anthologies including <em>Found Object, Global City Review, Resister, Lungfull!, the St. Marks Poetry Project Newsletter, Red Shift, National Poetry Magazine of the Lower East Side, Milk, IKON, Red Tape, Sensitive Skin, New Observations</em>, and others. She has read her work and had it performed in many venues. She is also the writer of the self-published <em>Do-Doh</em> and the publisher and editor in chief of the <em>I.H.I.Y.W. Newsletter</em>, which specializes in analysis of contemporary developments. Her skin is in fact sensitive to a fault!

<p class="contributors"><strong>Darius James</strong> (aka Dr. Snakeskin) is the black American author of <em>That's Blaxploitation: Roots of the Baadasssss 'Tude (Rated X by an All'Whyte Jury)</em>, an unorthodox, semi-autobiographical history of the blaxploitation film genre, and <em>Negrophobia: An Urban Parable</em>, a satiric novel written in screenplay form. He's currently working on the script for the upcoming Web Film <em>Misanthropicon</em>.

<p class="contributors"><a href="http://www.stewarthomesociety.org" target="_blank"><strong>Stewart Home</strong></a> left school at the age of sixteen, he first signed on the dole in the late seventies, and last claimed unemployment benefits in the mid-nineties. He has never held down a regular job for more than a few months at a time. On those rare occasions when he's been forced to work, Home has taken employment as a factory labourer, agricultural labourer, shop assistant, office clerk and art class model.

<p class="contributors">Brooklyn-based writer <strong>Michael A. Gonzales</strong> has written for <em>Stop Smiling, Wax Poetics, New York, High Times</em> and the <em>Village Voice</em>. His essay on legendary writer Chester Himes was reprinted in <em>Best African-American Essays 2010</em> (Random House) edited by Gerald Early. In addition, Gonzales has published short stories in collections and online journals including <em>Needle, Beat to a Pulp, A Twist of Noir, CrimeFactory, Brown Sugar 2, Bronx Biannual, The Darker Mask (Heroes From the Shadows)</em> and <em>Coon Bidness</em>. He blogs at <a href="http://blackadelicpop.blogspot.com" target="_blank">blackadelicpop.blogspot.com</a>.

<p class="contributors"><strong>Merry Fortune</strong> is a writer of Native American and German descent. She (with Robert Martens) was the co-editor of <em>Pagan Place</em>, a nationally distributed arts' zine. She is the author of <em>Ghosts By Albert Ayler, Ghosts By Albert Ayler</em> (Futurepoem books, 2004). The work featured in Sensitive Skin is from a forthcoming collection of poems and stories titled <em>Deep Red Guild</em> (Straw Gate Books).

<p class="contributors"><strong>Michael Carter</strong> published <a href="http://dlib.nyu.edu/findingaids/html/fales/" target="_blank"><em>Red Tape</em></a> magazine from 1980 to 1992. His work has been published in various Unbearables publications,<em> Between C & D</em> and <em>Peau Sensible</em>.

<p class="contributors">After being expelled from the art division of Bennington College, <strong>Hal Hirshorn</strong> went to Venice, Italy and came to New York where he completed his education in and around the city. He uses 19th century equipment and techniques to create found photographs of images whose original subject and meaning have been forgotten. His glossy prints are albumized salt prints that have been coated with a solution of egg whites, while the matte prints are created on plain salted paper. His work has been shown at Paris Photo, the Royal Academy in London and various other venues in London with Pierre Spake, the Association of International Photography Art Dealers with Thomas Harris in New York and the James Graham & Sons gallery in New York.

<p class="contributors"><strong>Barbara Greczny</strong> holds a BFA from OCAD University and is currently in her final year of the Documentary Media MFA program at Ryerson University. She was a member of the <a href="http://www.cubephotography.com/" target="_blank">Symbiosis</a> collective from 1992 until their last site specific show in 1997. The Bank of Symbiosis explored the complex economic and emotional relationship between bank and client, institution and individual. The Bank of Symbiosis became a repository of ideas about 'economy' and surplus, surveillance/privacy and social/monetary exchange.

<p class="contributors"><strong>J. Boyett</strong> has had some plays produced in New York (including "Pornophiles," "Sibling Ribaldry," "The Final Analysis," "Someone Borrowed, Someone Screwed," "A Beautiful Circle of Love and Acceptance," "Love Stinks," "School Romance," and "The Victim"), has published with the literary collective The Unbearables, and is editor of the online magazine, <a href="http://saltimbanquereview.com/" target="_blank"><em>The Saltimbanque Review</em></a>.

<h2 class="small-subhead">Issue 3</h2>

<p class="contributors"><strong>Ted Barron</strong> has been making photographs and films since he was 12 years old and growing up in St. Louis. As a teenager he ran away and joined the circus. He soon found himself living in New York City which he has called home ever since. His work has been seen in numerous art and music publications including <em>Yeti</em> and <em>Bald Ego</em> as well as album covers by Steve Earle and Laura Cantrell.  He edits and occasionally writes about music at the popular blog <a target="_blank" href="http://boogiewoogieflu.blogspot.com/">Boogie Woogie Flu</a>, as well as maintaining his archive of photographs at <a target="_blank" href="http://dailypixeltwentyten.blogspot.com/">Daily Pixel: Twenty-Ten</a>.

<p class="contributors"><strong><a target="_blank" href="http://www.craigclevenger.com/">Craig Clevenger</a></strong> was born in Dallas, Texas and currently lives in San Francisco, California. He is the author of <a target="_blank" href="http://www.amazon.com/gp/product/1931561486?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1931561486"><em>The Contortionist's Handbook</em></a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1931561486" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> (MacAdam/Cage, 2002), and <a target="_blank" href="http://www.amazon.com/gp/product/1596921021?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1596921021"><em>Dermaphoria</em></a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1596921021" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> (MacAdam/Cage, 2005). His novels have been optioned for feature films and together have been published in over a dozen languages. Clevenger is currently at work on his third novel. He frequently posts to a collaborative website, <a target="_blank" href="http://www.welcometothevelvet.com/">Welcome to the Velvet</a>.

<p class="contributors"><strong>Rebecca Weiner Tompkins</strong> has played and recorded acoustic and amplified four- and five-string violin and viola with Karen and the Sorrows, Life in a Blender, Chief, Scott McClatchy, Patti Smith and many others. Her poems have appeared in various journals including <em>Poetry</em> magazine, <em>Seneca Review</em>, <em>The Antioch Review</em>, <em>Ploughshares</em>, <em>Pequod</em>, and <em>The Mercury Reader</em>. In 2009 she gave a TEDx talk in Canterbury, Kent UK, called <em>Sensing Convergences</em>, the title of a manuscript she's writing. After 25 years in the East Village, NYC she crossed the river to live near Prospect Park in Brooklyn where she spends a lot of time wandering about with her dogs.



<p class="contributors"><a target="_blank" href="http://eddiewoods.nl/"><strong>Eddie Woods</strong></a> (born May 8, 1940 in New York) is a poet/prose writer, editor and publisher who lived and traveled in various parts of the world, both East and West, before eventually settling in Amsterdam, Holland, where in 1978 he started <em>Ins & Outs</em> magazine and two years later founded Ins & Outs Press.

<p class="contributors"><strong>John Farris</strong> is a long-time denizen of the Lower East Side - he still lives above the Bullet Space Gallery on East 3rd Street. He has been published in <em>Red Tape</em>; <em>Gathering of the Tribes</em>; <a target="_blank" href="http://www.amazon.com/gp/product/1560252278?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1560252278"><em>The Outlaw Bible of American Poetry</em></a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1560252278" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> and <em>Let Loose on the World: Celebrating Amiri Baraka at 75</em>. His new novel, <em>The Ass's Tale</em> (Autonomedia) will be available in late September, 2010. "There is a hidden blessing in knowing John Farris, deeply hidden." - David Hammons

<p class="contributors"><strong>Ron Kolm</strong> (born 1947) is an American poet, editor, activist and bookseller, based in New York City. Kolm came to New York in 1970 and got a job at the Strand bookstore, where he worked with Tom Verlaine and Patti Smith. In 1985, Kolm, Bart Plantenga, Mike Golden, Max Blagg and Peter Lamborn Wilson founded the <a target="_blank" href="http://www.unbearables.com/blog/">Unbearables</a>, a loose collective of poets and artists. Kolm has been one of the editors of their anthologies: Unbearables (1995), Crimes of the Beats (1998), Help Yourself! (2002) and <a target="_blank" href="http://www.amazon.com/gp/product/1570271992?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1570271992">The Worst Book I Ever Read</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1570271992" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" /> all published by Autonomedia. Kolm's own publications include The Plastic Factory (1989, Red Dust), Welcome to the Barbecue (Low-Tech Press, 1990) and Rank Cologne (P.O.N. Press, 1991). His work can also be found, along with the other Unbearables, in <a target="_blank" href="http://www.amazon.com/gp/product/1560252278?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1560252278">The Outlaw Bible of American Poetry</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1560252278" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, and in <a target="_blank" href="http://www.amazon.com/gp/product/0814740111?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=0814740111">Up Is Up, But So Is Down: New York's Downtown Literary Scene, 1974-1992</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=0814740111" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />. He has collaborated on a novel, <a target="_blank" href="http://www.amazon.com/gp/product/1570271712?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1570271712">Neo Phobe</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1570271712" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, written with Jim Feast (Unbearable Books, 2006).

<p class="contributors"><strong><a target="_blank" href="http://www.spuytenduyvilmusic.com">Spuyten Duyvil</a></strong> wanders the last 100 years of American music conjuring embittered civil war veterans, recalcitrant small town bawds, suicidal bureaucrats, star crossed lovers and brave hearted fools navigating the mysteries of daily life.

<p class="contributors"><p class="contributors"><strong>Dan Safoer</strong> - When he isn't up to no good, Dan Sofaer lives in the Catskills near Woodstock. He has published his poems in Open City and <a target="_blank" href="http://www.fulcrumpoetry.com">Fulcrum</a> and was a bassist in the Oakland-based Giant Haystacks.


<h2 class="small-subhead">Issue 2</h2>
<p class="contributors"><strong>Albert Kresch</strong> is a New York School painter who lives and works in Brooklyn, New York. One of the original members of the Jane Street Gallery in the 1930s, he exhibited in later years at Tibor de Nagy Gallery and Salander-O’Reilly Galleries. He is best known for landscape and still life compositions painted with evocatively rhythmic forms and vibrant colors.

<p class="contributors"><strong><a target="_blank" href="http://unnaturalbeings.blogspot.com/">Rob Hardin</a></strong> is the author of <a target="_blank" href="http://www.amazon.com/gp/product/1573660485?ie=UTF8&tag=sensskinmaga-20&linkCode=as2&camp=1789&creative=9325&creativeASIN=1573660485">Distorture</a><img src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&l=as2&o=1&a=1573660485" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />, a callously florid collection of short stories that seduced the Firecracker Award into being won and then told the award it should really start seeing other people. His fiction and essays have manipulated their way into the anthologies <a target="_blank" href="http://www.amazon.com/gp/product/0932511724?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0932511724">Avant-Pop: Fiction for a Daydream Nation</a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0932511724" border="0" alt="" width="1" height="1" />, Postmodern Culture, In the Slipstream,<a target="_blank" href="http://www.amazon.com/gp/product/0380779153?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0380779153">Forbidden Acts</a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0380779153" border="0" alt="" width="1" height="1" />, <a target="_blank" href="http://www.amazon.com/gp/product/0822311682?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0822311682">Storming the Reality Studio: A Casebook of Cyberpunk &amp; Postmodern Science Fiction</a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0822311682" border="0" alt="" width="1" height="1" />, Mississippi Review’s Best of the Web and An Exaltation of Forms. As a studio musician, he has intimidated others into using him on more than forty albums. Currently beating a new novel into mute acquiescence and systematically demoralizing an album of songs for string trio, he enjoys manly distractions such as writing about himself in the third person and posing as a bankrupt philanthropist suffering from Werewolf Syndrome. (Bartender: "Madam, this glass of water is from the grinning furball in tails.")

<p class="contributors"><strong>Emily XYZ</strong> is an American writer and performer best known for her spoken-word poetry for multiple voices.  Born in upstate New York, she moved to New York City in 1982 and was active in the downtown Manhattan performance art and music scene.  In 1992 XYZ began working with actress Myers Bartlett. The pair has toured extensively in the U.S. and Canada as members of the seminal New York City spoken-word collectives The Nuyorican Poets Café Live! and Real Live Poetry, and on their own. A book and audio CD collection of XYZ’s work for two voices, entitled The Emily XYZ Songbook, was published in 2004.  Her poem “Slot Machine” was featured in the nationally broadcast Public Television [PBS] series The United States of Poetry.  Her poems have also been published in several anthologies, including <a target="_blank" href="http://www.amazon.com/gp/product/0814740111?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0814740111"><em>Up Is Up, But So Is Down: New York's Downtown Literary Scene, 1974-1992</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0814740111" border="0" alt="" width="1" height="1" />, and <a target="_blank" href="http://www.amazon.com/gp/product/0805032576?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0805032576"><em>Aloud: Voices from the Nuyorican Poets Cafe</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0805032576" border="0" alt="" width="1" height="1" />. She is currently the <a target="_blank" title="Art Queensland Poet in Residence" href="http://poetinresidence.wordpress.com/" target="_blank">Arts Queensland Poet in Residence</a>.

<p class="contributors"><strong>Christian X. Hunter</strong> - Writing by Christian X Hunter aka Keshav Das, a former coordinator at the Poetry Project at St. Marks In The Bowery, has appeared in publications such as The World, Semiotext, and Autonomedia Press. He's written for New York Press and American Book Review. His new book <em>In His Hands</em>, a collection of stories about the Indian saint Neem Karoli Baba is coming out this coming out this fall from Cambridge Press. In order to support his writing habit he owns and runs <a target="_blank" title="Keshav Music" href="http://www.keshav-music.com/">Keshav Music Imports</a> in New York which sells and repairs Indian musical instruments.

<p class="contributors"><strong>B. Kold</strong> - One of the original contributors to Sensitive Skin, he moved to a yurt in the Lolo National Forrest in Montana sometime in the early 90's for "health reasons". These days he mainly tends his goats, makes goat cheese that he sells at the local farmer's market, and eats goat cheese. Occasionally, he dusts off one of his old manuscripts and sends it in.

<p class="contributors"><a title="Kurt Wolf Music" href="http://web.mac.com/kwolf13/iWeb/wolfmusic/Welcome.html" target="_blank"><strong>Kurt Wolf</strong></a> is known for his contributions to downtown noise rock acts, Pussy Galore, Boss Hog, Loudspeaker, Emma Peel, Foetus Inc.<a target="_blank" title="Lapis Lazuli" href="http://www.lapislazulimusic.com" target="_blank"><strong> Lapis Lazuli</strong></a> is a solo instrumental project written, produced, and performed by Kurt Wolf on laptop, guitar, and analog synth.

<p class="contributors"><a title="Rebecca Gaffney" href="www.rebeccagaffney.com" target="_blank"><strong>Rebecca Gaffney</strong></a> has done  shows at Movement Research Festival, NY Eye and Ear, PS1, and helped curate  Monkeytown (R.I.P.) Semiennial 5 and create and curate videvent Spun,  and has also appeared in Capricious magazine. You can find her work online at <a href="http://www.vimeo.com/user3458280/videos" target="_blank">Vimeo</a>.

<p class="contributors"><strong><a title="Nettertainment" href="http://nettertainment.blogspot.com/" target="_blank">Mark Netter</a></strong>, based in Santa Monica, is constantly striving to know what the heck is  going on, no I mean really What the Heck is Going On?
<h2 class="small-subhead">Issue 1</h2>
<p class="contributors"><strong><a target="_blank" href="http://eastofbowery.blogspot.com/">Drew Hubner</a></strong> is the author of <a target="_blank" href="http://www.amazon.com/gp/product/0684857715?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0684857715"><em>American by Blood: A Novel</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0684857715" border="0" alt="" width="1" height="1" /> and <a target="_blank" href="http://www.amazon.com/gp/product/0743212789?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0743212789"><em>We Pierce: A Novel</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0743212789" border="0" alt="" width="1" height="1" />. He lives in New York City with his wife Sarah and children Henry, August and Eleanor.  He works as a Lecturer of English at Hostos Community College of the City University of New York.

<p class="contributors"><strong><a target="_blank" href="http://paduakings.blogspot.com/">Jose Padua</a></strong> has written poetry and fiction for in Bomb, Salon.com, Exquisite Corpse, Another Chicago Magazine, Unbearables, <a target="_blank" href="http://www.amazon.com/gp/product/1570270694?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=1570270694"><em>Crimes of the Beats</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=1570270694" border="0" alt="" width="1" height="1" />, <a target="_blank" href="http://www.amazon.com/gp/product/0814740111?ie=UTF8&amp;tag=sensskinmaga-20&amp;linkCode=as2&amp;camp=1789&amp;creative=9325&amp;creativeASIN=0814740111"><em>Up Is Up, But So Is Down: New York's Downtown Literary Scene, 1974-1992</em></a><img class=" uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid uvotqexopphmzaxuhjid" style="border: none !important; margin: 0px !important;" src="http://www.assoc-amazon.com/e/ir?t=sensskinmaga-20&amp;l=as2&amp;o=1&amp;a=0814740111" border="0" alt="" width="1" height="1" />, and many other journals and anthologies. He has also written features and reviews for NYPress, Washington City Paper, the Brooklyn Rail, and the New York Times. He has read his work at the Lollapalooza Festival, CBGBs, the Knitting Factory, the Public Theater, the Living Theater, the Nuyorican Poets’ Café, the St. Mark’s Poetry Project, the Black Cat Club, the Washington Project for the Arts, and many other venues. He and his wife, the poet Heather Davis, are the authors of the blog <a target="_blank" href="http://shenandoahbreakdown.wordpress.com/">Shenandoah Breakdown</a>. They live with their daughter in Virginia’s Shenandoah Valley.

<p class="contributors"><strong><a target="_blank" href="http://www.justinefrischmann.net">Justine Frischmann</a></strong> is an artist and musician who has performed and exhibited in Europe, North America, Japan and Australia. She wrote and performed with <a target="_blank" href="http://en.wikipedia.org/wiki/Elastica">Elastica</a> and, more recently, has written and produced for a number of artists including M.I.A. She has a degree in architecture from University College London, has studied Contemplative Art at Naropa University, and Fine Art at the San Francisco Art Institute. Her work has been reviewed in many publications including the <em>London Sunday Times</em> (Art and Culture), the <em>LA Times</em>, and the <em>London Telegraph</em>. She was a presenter and writer on the <em>South Bank Show</em>, the UK's oldest and most respected arts program, and has presented programs on art, music and architecture for BBC TV, BBC World TV (Arts), and BBC Radio 6. She has written about art and culture for magazines such as <em>ID</em> and <em>The Face</em> (UK), and was a judge for the Sterling Prize. She now lives and works in the Bay Area.

<p class="contributors"><strong><a target="_blank" href="http://www.facebook.com/bart.plantenga">bart plantenga</a></strong> is also the author of <a target="_blank" href="http://www.3ammagazine.com/short_stories/fiction/paris_sex_tete/page_1.html">Wiggling Wishbone</a> and <a target="_blank" href="http://bookstore.autonomedia.org/index.php?main_page=pubs_product_book_info&products_id=419">Spermatagonia: The Isle of Man</a>. His book <a target="_blank" href="http://www.routledge.com/shopping_cart/products/product_detail.asp?sku=&amp;isbn=9780415939904&amp;parent_id=&amp;pc=/shopping_cart/search/search.asp?search%3Dyodel">YODEL-AY-EE-OOOO: The Secret History of Yodeling Around the World</a> received worldwide attention. He is working on a new novel, <a target="_blank" href="http://www.3ammagazine.com/short_stories/fiction/paris_sex_tete/page_1.html">Paris Sex Tete</a> and a new book on yodeling <a target="_blank" href="http://bartyodel2.wordpress.com/">Yodel in HiFi</a>. His radio show <a target="_blank" href="http://bartyodel.wordpress.com/">Wreck This Mess</a> has been on the air on WFMU [NY], Radio Libertaire [Paris], Radio 100 and currently Radio Patapoe [Amsterdam] since 1986. He lives in Amsterdam.

<p class="contributors"><strong><a target="_blank" href="http://www.thecodeinternational.com">Steve Horowitz</a></strong> is a creator of odd but highly accessible sounds and a diverse and prolific musician, with an output spanning the worlds of film, television, games, concerts, and recordings. Steve wrote the original score to the hit film Super Size Me, composed music for literally hundreds of games &amp; won a Grammy award for engineering the multi-artist True Life Blues: The Songs of Bill Monroe [Sugar Hill], 1996's winner for best bluegrass album. Steve tours and plays with his group the code ensemble.

<p class="contributors"><strong><a target="_blank" href="http://soldbyvolume.blogspot.com/">Bob Bannister</a></strong> moved to NYC in the 1980s and began writing about music for the East Village Eye, Op and Ear magazines, then founded the band Fire In The Kitchen and started producing the fanzine On Site. By the early 90s, he was also playing with Tono-Bungay, Vodka, Vineland, Cat Power as well as guest appearances with Dave Soldier, Timber, Sleepyhead and Versus, among others.  Bob's writing on music can occasionally be found in Time Out New York, plus there is a slew of book reviews at <a target="_blank" href="http://www.goodreads.com/review/list/82944-bob?view=reviews">goodreads.com</a>.

    				 </section> <!-- end article section -->
						
						    <footer class="article-footer">
							  							
						    </footer> <!-- end article footer -->
						    
					
					    </article> <!-- end article -->
								
				    </div> <!-- end #main -->
    
				    <?php get_sidebar(); ?>
				    
				</div> <!-- end #inner-content -->
    
			</div> <!-- end #content -->
<?php get_footer(); ?>